# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">=2.2.19"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-stream-8"

  config.vm.hostname = "icarus"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  # Flask dev server
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -ex

    # install Puppet
    /usr/bin/dnf -y install https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
    /usr/bin/dnf -y install puppet-agent ruby

    # install librarian-puppet and Puppet modules
    /usr/bin/gem install librarian-puppet -v 3.0.1 --no-document
    /usr/local/bin/librarian-puppet config path /opt/puppetlabs/puppet/modules --global
    /usr/local/bin/librarian-puppet config tmp /tmp --global
    PATH="${PATH}:/opt/puppetlabs/bin" && cd /vagrant/deployment/puppet && /usr/local/bin/librarian-puppet install
  SHELL

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "deployment/puppet/manifests"
    puppet.manifest_file = "site.pp"
   end
end
